# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6541bc9f24d97c3a9d9e73105884317681f316ec5fe8d50500dabf0d8d795e70636d504af816c33420fa36a8c55249ae7c170edf0411f07a420bbbc2e358551a

test:
  secret_key_base: 00134e7c7b40ae1b6b7f203b8fca4c897f3b44c4b4cfdb8e21d25ba5ad0e569c8d217c56e7b1521021e30ab98a866c9ab6e8492524c60620cfefb369b2d71e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
